### ISSUE TITLE
One Step Closer

### ISSUE THREAD

**Issue by DenisCarriere** [mclaeysb/simplepolygon#13]
Just noticed some positive changes in `v1.2.0`.

Still not 100% there yet, but better than before, only splits 1 geometry.

## Using this [`complex.geojson`](https://github.com/Turfjs/turf/blob/master/packages/turf-unkink-polygon/test/in/complex.geojson)

![image](https://user-images.githubusercontent.com/550895/28884499-20b4cd4a-7780-11e7-90ab-f9fa4048aa98.png)

## Before to `v1.2.0`

![image](https://user-images.githubusercontent.com/550895/28884476-07ad4c32-7780-11e7-892e-545c48142218.png)

## Now `v1.2.0`

![image](https://user-images.githubusercontent.com/550895/28884492-147777bc-7780-11e7-8c98-3a75563cbac7.png)

**Comment by mclaeysb** [comment]
Did you `npm update` to use the newest version of `geojson-polygon-self-intersections`? As mentioned in #7, this should fix your issue!

**Comment by DenisCarriere** [comment]
🤔  I don't get it.. why would I need to `npm update`? Why wouldn't you update your dependencies directly in your module?

**Comment by DenisCarriere** [comment]
Still no change... Even hardcoded the dependencies to the specific latest versions:

```json
"dependencies": {
  "geojson-polygon-self-intersections": "1.1.2",
  "simplepolygon": "1.2.0"
}
```

**Comment by DenisCarriere** [comment]
We've added it to your local tests, same results.

https://github.com/mclaeysb/simplepolygon/blob/master/test/out/complex.geojson

**Comment by mclaeysb** [comment]
If my understanding is correct, `npm update` will update all dependancies, including `geojson-polygon-self-intersections` to 1.1.2. Just pushed simplepolygon again te make sure it's requiring it.
 
`test/in/complex.geojson` seems to give [correct results](http://geojson.io/#id=gist:anonymous/b6a9950c8740f71fde4376b239f93313&map=5/-25.998/127.661) here. Not sure why you're getting something else. How could we find out?

**Comment by DenisCarriere** [comment]
Oops 🤓 Yea I thought it was only returning 2 features, but that's because the output color ramp only had two colors.

👍 Works

> Handling these kinds of "complex" shapes can be a mess, I wouldn't want to attempt doing this, thanks for help & contributions to this module!

![image](https://user-images.githubusercontent.com/550895/28942419-4253b2ba-7869-11e7-9584-ef7f58611cb2.png)

**Comment by mclaeysb** [comment]
Great! Glad I could be of help. Congrats with the turf release btw!

**Comment by DenisCarriere** [comment]
Thanks! 👍 Things tend to blow up every time we push a big release, lol that's why I noticed your library changed.

Any chance that `simplepolygon` will support MultiPolygon?

We've got [`flattenEach`](https://github.com/Turfjs/turf/tree/master/packages/turf-meta#flatteneachcallback) that can help with that.

[Also noticed](https://github.com/mclaeysb/simplepolygon/blob/master/index.js#L40-L46) you might be another user of this newly proposed [`ringEach`](https://github.com/Turfjs/turf/issues/881) feature in `@turf/meta` (from @rowanwins ).

**Comment by mclaeysb** [comment]
Thanks for pointing this out. I don't currently have plans to develop `simplepolygon`further. Will let you know when that's the case, and take a look at these then!

**Comment by DenisCarriere** [comment]
👍 No worries, I know it's a lot of work :) If ever you do, check out those new Turf features.
