### ISSUE TITLE
allIsectsAsIsectRbushTreeItem is not declared

### ISSUE THREAD

**Issue by amenadiel** [mclaeysb/simplepolygon#14]
@mclaeysb

In line
https://github.com/mclaeysb/simplepolygon/blob/23030c354ed3cc550bb0f1caec92a95d88842695/index.js#L105

Variable `allIsectsAsIsectRbushTreeItem` isn't declared as `var`, `let` or `const`. 

In some environments this amounts for the variable becoming global. Linters complain about it being undeclared, and QUnit doesn't pass tests if 

`QUnit.config.noglobals = true;` config option is used.

Do you think you could declare this variable without side effects?

**Comment by mclaeysb** [comment]
Yes, we could. Please submit a PR, I'll happily accept it!

**Comment by amenadiel** [comment]
I've created it #15

**Comment by mclaeysb** [comment]
Solved by #15, closing!
