### ISSUE TITLE
process.hrtime not available in browser

### ISSUE THREAD

**Issue by DenisCarriere** [mclaeysb/simplepolygon#5]
`process.hrtime` is not a valid function in the browser.

Have this ever been tested in the browser? Tests are passing fine in NodeJS.

https://github.com/mclaeysb/simplepolygon/search?utf8=%E2%9C%93&q=process.hrtime&type=

Might be handy to set up a simple `/docs` folder with an `index.html` and a browser friendly build to simply test this library in the browser. Here's a "minimalistic" approach I've been doing for some of my libraries https://github.com/DenisCarriere/slippy-tile/tree/master/docs.

I can send a PR to include a simple Rollup config that builds the bundle, let me know.

For this type of debugging/timings, you could look into including [`debug`](https://www.npmjs.com/package/debug) for your internal testing/debugging.

**Comment by mclaeysb** [comment]
Closed thanks to #6
