### ISSUE TITLE
Complex polygon only return two parts

### ISSUE THREAD

**Issue by DenisCarriere** [mclaeysb/simplepolygon#7]
Complex polygons should return multiple parts (only return with two parts).

https://gist.github.com/a49494d38ded757824ba1f325bf26940
![image](https://cloud.githubusercontent.com/assets/550895/24757759/207d3224-1aae-11e7-8cd8-4a307925443f.png)

**Comment by mclaeysb** [comment]
From the image you added it indeed looks like the algorithm failed to correctly identify the simple polygons of the input polygons. I advise you to turn on the debug parameter and follow how the algorithm walks over the edges. This way you can find out where it makes its mistake!

**Comment by DenisCarriere** [comment]
@mclaeysb kinda hard a troubleshoot a library I didn't build, I would have no clue where to start. This why I added the dynamic testing in [`test/in`](https://github.com/mclaeysb/simplepolygon/tree/master/test/in), here are the results of [`test/out/complex.geojson`](https://github.com/mclaeysb/simplepolygon/blob/master/test/out/complex.geojson)

**Comment by mclaeysb** [comment]
Just had some time to look in to this. Was due the dependancy `geojson-polygon-self-intersections` which had some trouble with the exactly vertical line (meridian). Fixed that issue in the dependancy and published to npm. Running `npm update` inside the `simplepolygon` directory should solve this.
