### ISSUE TITLE
Polygon with holes (inners are replaced as outers)

### ISSUE THREAD

**Issue by DenisCarriere** [mclaeysb/simplepolygon#8]
Polygon with holes (inners are replaced as outers).

https://gist.github.com/c7c1343e8102c506b1f256755446c531
![image](https://cloud.githubusercontent.com/assets/550895/24757656/dc9ac4fe-1aad-11e7-9ce5-8bd8edb24a3d.png)

**Comment by mclaeysb** [comment]
Can you detail on the specific issue here?

**Comment by DenisCarriere** [comment]
Well when you provide a polygon with a hole and pass it through `simplepolygon` the output becomes two outer polygons (instead of a single polygon with hole).

**Comment by mclaeysb** [comment]
`simplepolygon` was designed to help fix `turf-buffer`, and for it's usage there this is indeed the intended output: a featureCollection of one-ring polygons (with there winding, net winding and parent ring). 

If you want `simplepolygon` to process this differently in other use-cases, you can add a parameter that triggers a different action when `numSelfIsect == 0` ([here](https://github.com/mclaeysb/simplepolygon/blob/master/index.js#L59)) and returns the input feature in stead of the collection of one-ring polygon.

**Comment by DenisCarriere** [comment]
@mclaeysb Thanks for the clarity, I believe the metadata of inners & outers can be retrieve from `parent`, `winding` & `netWinding` properties. I thought this module was only dealing with self-intersecting polygons and not changing the inner rings of the polygons to outers.
